name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
    
    - name: Add server to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.DIGITALOCEAN_IP }} >> ~/.ssh/known_hosts
    
    - name: Deploy to DigitalOcean
      run: |
        ssh -o UserKnownHostsFile=~/.ssh/known_hosts root@${{ secrets.DIGITALOCEAN_IP }} << 'EOF'
          cd /opt/nuestrasrecetas
          git pull origin main
          
          # Build and restart containers
          docker compose down
          docker compose build --no-cache app
          docker compose --profile with-nginx up -d
          
          # Clean up old images
          docker image prune -f
        EOF